version: "3.8"
services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - "3306:3306"
  app:
    build: 
      context: ./myapp
      dockerfile: Dockerfile-app
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: on-failure
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"

