FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY ./public/images/* /usr/share/nginx/images/
COPY ./public/javascripts/*.js /usr/share/nginx/javascripts/
COPY ./public/js/*.js /usr/share/nginx/js/
COPY ./public/stylesheets/*.css /usr/share/nginx/css/
