FROM node

# Create app directory
WORKDIR /myapp

# Install app dependencies
COPY package*.json /myapp


RUN npm install

# Copying rest of the application to app directory
COPY . /myapp

# Expose the port and start the application
Expose 3000

CMD ["npm", "start"]